"""initial_schema

Revision ID: 8eac5f09ed26
Revises: 
Create Date: 2026-03-29 20:08:52.070367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eac5f09ed26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_analytics_day'), table_name='chat_analytics')
    op.drop_index(op.f('idx_chat_analytics_session'), table_name='chat_analytics')
    op.drop_table('chat_analytics')
    op.drop_index(op.f('idx_customer_notes_customer'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_column('ai_buddies', 'usecase_id')
    op.drop_index(op.f('idx_capability_requests_customer'), table_name='capability_requests')
    op.drop_index(op.f('idx_capability_requests_status'), table_name='capability_requests')
    op.alter_column('content_guard_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_content_guard_logs_created'), table_name='content_guard_logs')
    op.drop_index(op.f('idx_content_guard_logs_customer'), table_name='content_guard_logs')
    op.create_index(op.f('ix_content_guard_logs_created_at'), 'content_guard_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_guard_logs_customer_id'), 'content_guard_logs', ['customer_id'], unique=False)
    op.drop_index(op.f('idx_memory_items_category'), table_name='memory_items')
    op.drop_index(op.f('idx_payments_customer'), table_name='payments')
    op.alter_column('stock_alerts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CHF'::character varying"))
    op.alter_column('stock_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('stock_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stock_alerts_active'), table_name='stock_alerts', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_stock_alerts_customer'), table_name='stock_alerts')
    op.drop_constraint(op.f('stock_alerts_customer_id_fkey'), 'stock_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'stock_alerts', 'customers', ['customer_id'], ['id'])
    op.alter_column('training_reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('training_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_training_reminders_active'), table_name='training_reminders', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_training_reminders_customer'), table_name='training_reminders')
    op.drop_index(op.f('idx_window_boards_customer'), table_name='window_boards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_window_boards_customer'), 'window_boards', ['customer_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_training_reminders_customer'), 'training_reminders', ['customer_id'], unique=False)
    op.create_index(op.f('idx_training_reminders_active'), 'training_reminders', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('training_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'stock_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('stock_alerts_customer_id_fkey'), 'stock_alerts', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_stock_alerts_customer'), 'stock_alerts', ['customer_id'], unique=False)
    op.create_index(op.f('idx_stock_alerts_active'), 'stock_alerts', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('stock_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('stock_alerts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CHF'::character varying"))
    op.create_index(op.f('idx_payments_customer'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('idx_memory_items_category'), 'memory_items', ['customer_id', 'category'], unique=False)
    op.drop_index(op.f('ix_content_guard_logs_customer_id'), table_name='content_guard_logs')
    op.drop_index(op.f('ix_content_guard_logs_created_at'), table_name='content_guard_logs')
    op.create_index(op.f('idx_content_guard_logs_customer'), 'content_guard_logs', ['customer_id'], unique=False)
    op.create_index(op.f('idx_content_guard_logs_created'), 'content_guard_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('content_guard_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_capability_requests_status'), 'capability_requests', ['status'], unique=False)
    op.create_index(op.f('idx_capability_requests_customer'), 'capability_requests', ['customer_id'], unique=False)
    op.add_column('ai_buddies', sa.Column('usecase_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('customer_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_notes_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_notes_pkey'))
    )
    op.create_index(op.f('idx_customer_notes_customer'), 'customer_notes', ['customer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('chat_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_hash', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assistant_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_type', sa.VARCHAR(length=50), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'de'::character varying"), autoincrement=False, nullable=True),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hour_of_day', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('system_prompt_name', sa.VARCHAR(length=100), server_default=sa.text("'Standard'::character varying"), autoincrement=False, nullable=True),
    sa.Column('tools_used', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('memory_facts', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_analytics_pkey'))
    )
    op.create_index(op.f('idx_chat_analytics_session'), 'chat_analytics', ['session_hash'], unique=False)
    op.create_index(op.f('idx_chat_analytics_day'), 'chat_analytics', [sa.literal_column('day DESC')], unique=False)
    # ### end Alembic commands ###
